# return directory list except 'CMakeFiles'
MACRO(SUBDIRLIST result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF((IS_DIRECTORY ${curdir}/${child}) AND (NOT ${child} STREQUAL "CMakeFiles"))
      LIST(APPEND dirlist ${child})
    ENDIF()
  ENDFOREACH()
  SET(${result} ${dirlist})
ENDMACRO()
